/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppProcurementRequestsRouteImport } from './routes/app.procurement.requests'
import { Route as AppHrEmployeesRouteImport } from './routes/app.hr.employees'
import { Route as AppHrApprovalsRouteImport } from './routes/app.hr.approvals'
import { Route as AppFinanceTransactionsRouteImport } from './routes/app.finance.transactions'
import { Route as AppFinanceApprovalsRouteImport } from './routes/app.finance.approvals'
import { Route as AppCrmTasksRouteImport } from './routes/app.crm.tasks'
import { Route as AppCrmPipelineRouteImport } from './routes/app.crm.pipeline'
import { Route as AppCrmDealsRouteImport } from './routes/app.crm.deals'
import { Route as AppCrmContactsRouteImport } from './routes/app.crm.contacts'
import { Route as AppCrmAccountsRouteImport } from './routes/app.crm.accounts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRequestsRoute = AppProcurementRequestsRouteImport.update({
  id: '/procurement/requests',
  path: '/procurement/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppHrApprovalsRoute = AppHrApprovalsRouteImport.update({
  id: '/hr/approvals',
  path: '/hr/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceTransactionsRoute = AppFinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceApprovalsRoute = AppFinanceApprovalsRouteImport.update({
  id: '/finance/approvals',
  path: '/finance/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmTasksRoute = AppCrmTasksRouteImport.update({
  id: '/crm/tasks',
  path: '/crm/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmPipelineRoute = AppCrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmDealsRoute = AppCrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmContactsRoute = AppCrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmAccountsRoute = AppCrmAccountsRouteImport.update({
  id: '/crm/accounts',
  path: '/crm/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/crm/accounts': typeof AppCrmAccountsRoute
  '/app/crm/contacts': typeof AppCrmContactsRoute
  '/app/crm/deals': typeof AppCrmDealsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/crm/tasks': typeof AppCrmTasksRoute
  '/app/finance/approvals': typeof AppFinanceApprovalsRoute
  '/app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/app/hr/approvals': typeof AppHrApprovalsRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/procurement/requests': typeof AppProcurementRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/crm/accounts': typeof AppCrmAccountsRoute
  '/app/crm/contacts': typeof AppCrmContactsRoute
  '/app/crm/deals': typeof AppCrmDealsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/crm/tasks': typeof AppCrmTasksRoute
  '/app/finance/approvals': typeof AppFinanceApprovalsRoute
  '/app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/app/hr/approvals': typeof AppHrApprovalsRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/procurement/requests': typeof AppProcurementRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/crm/accounts': typeof AppCrmAccountsRoute
  '/app/crm/contacts': typeof AppCrmContactsRoute
  '/app/crm/deals': typeof AppCrmDealsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/crm/tasks': typeof AppCrmTasksRoute
  '/app/finance/approvals': typeof AppFinanceApprovalsRoute
  '/app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/app/hr/approvals': typeof AppHrApprovalsRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/procurement/requests': typeof AppProcurementRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/$'
    | '/app/ai'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/marketing'
    | '/app/profile'
    | '/app/workflows'
    | '/app/crm/accounts'
    | '/app/crm/contacts'
    | '/app/crm/deals'
    | '/app/crm/pipeline'
    | '/app/crm/tasks'
    | '/app/finance/approvals'
    | '/app/finance/transactions'
    | '/app/hr/approvals'
    | '/app/hr/employees'
    | '/app/procurement/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/$'
    | '/app/ai'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/marketing'
    | '/app/profile'
    | '/app/workflows'
    | '/app/crm/accounts'
    | '/app/crm/contacts'
    | '/app/crm/deals'
    | '/app/crm/pipeline'
    | '/app/crm/tasks'
    | '/app/finance/approvals'
    | '/app/finance/transactions'
    | '/app/hr/approvals'
    | '/app/hr/employees'
    | '/app/procurement/requests'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/$'
    | '/app/ai'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/marketing'
    | '/app/profile'
    | '/app/workflows'
    | '/app/crm/accounts'
    | '/app/crm/contacts'
    | '/app/crm/deals'
    | '/app/crm/pipeline'
    | '/app/crm/tasks'
    | '/app/finance/approvals'
    | '/app/finance/transactions'
    | '/app/hr/approvals'
    | '/app/hr/employees'
    | '/app/procurement/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement/requests': {
      id: '/app/procurement/requests'
      path: '/procurement/requests'
      fullPath: '/app/procurement/requests'
      preLoaderRoute: typeof AppProcurementRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr/employees': {
      id: '/app/hr/employees'
      path: '/hr/employees'
      fullPath: '/app/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr/approvals': {
      id: '/app/hr/approvals'
      path: '/hr/approvals'
      fullPath: '/app/hr/approvals'
      preLoaderRoute: typeof AppHrApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/transactions': {
      id: '/app/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/app/finance/transactions'
      preLoaderRoute: typeof AppFinanceTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/approvals': {
      id: '/app/finance/approvals'
      path: '/finance/approvals'
      fullPath: '/app/finance/approvals'
      preLoaderRoute: typeof AppFinanceApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/tasks': {
      id: '/app/crm/tasks'
      path: '/crm/tasks'
      fullPath: '/app/crm/tasks'
      preLoaderRoute: typeof AppCrmTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/pipeline': {
      id: '/app/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/app/crm/pipeline'
      preLoaderRoute: typeof AppCrmPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/deals': {
      id: '/app/crm/deals'
      path: '/crm/deals'
      fullPath: '/app/crm/deals'
      preLoaderRoute: typeof AppCrmDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/contacts': {
      id: '/app/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/app/crm/contacts'
      preLoaderRoute: typeof AppCrmContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/accounts': {
      id: '/app/crm/accounts'
      path: '/crm/accounts'
      fullPath: '/app/crm/accounts'
      preLoaderRoute: typeof AppCrmAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppCrmAccountsRoute: typeof AppCrmAccountsRoute
  AppCrmContactsRoute: typeof AppCrmContactsRoute
  AppCrmDealsRoute: typeof AppCrmDealsRoute
  AppCrmPipelineRoute: typeof AppCrmPipelineRoute
  AppCrmTasksRoute: typeof AppCrmTasksRoute
  AppFinanceApprovalsRoute: typeof AppFinanceApprovalsRoute
  AppFinanceTransactionsRoute: typeof AppFinanceTransactionsRoute
  AppHrApprovalsRoute: typeof AppHrApprovalsRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRoute
  AppProcurementRequestsRoute: typeof AppProcurementRequestsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppProfileRoute: AppProfileRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppCrmAccountsRoute: AppCrmAccountsRoute,
  AppCrmContactsRoute: AppCrmContactsRoute,
  AppCrmDealsRoute: AppCrmDealsRoute,
  AppCrmPipelineRoute: AppCrmPipelineRoute,
  AppCrmTasksRoute: AppCrmTasksRoute,
  AppFinanceApprovalsRoute: AppFinanceApprovalsRoute,
  AppFinanceTransactionsRoute: AppFinanceTransactionsRoute,
  AppHrApprovalsRoute: AppHrApprovalsRoute,
  AppHrEmployeesRoute: AppHrEmployeesRoute,
  AppProcurementRequestsRoute: AppProcurementRequestsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
